// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeletePath(arg1:string):Promise<void>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetCommonDirectories():Promise<Array<string>>;

export function GetDirectoryInfo(arg1:string):Promise<models.FileNode>;

export function GetUserHomeDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenInFinder(arg1:string):Promise<void>;

export function ScanDirectory(arg1:string):Promise<models.ScanResult>;

export function ValidatePath(arg1:string):Promise<boolean>;
