// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCommonDirectories() {
  return window['go']['main']['App']['GetCommonDirectories']();
}

export function GetDirectoryInfo(arg1) {
  return window['go']['main']['App']['GetDirectoryInfo'](arg1);
}

export function GetUserHomeDirectory() {
  return window['go']['main']['App']['GetUserHomeDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}
